language: go
os: linux
go: "1.14"

script:
  - go build .
  - ./releaser

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true

  target_branch: master
  commit_message: "[skip ci] Update data.json"

  on:
    branch: master